[package]
name = "rust-bbk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = { version = "4.0", features = ["derive"] }
hex = "0.4.3"
md-5 = "0.10.5"
openssl = "0.10.52"
pbkdf2 = "0.12.1"
rand = "0.8.5"
regex = "1.7.0"
rust-crypto = "0.2.36"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.10.6"
uuid = "1.3.2"
