[package]
name = "rust-bbk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
regex = "1.7.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
